### ISSUE TITLE
Manage dotplot windowsize

### ISSUE THREAD

**Issue by lalalagartija** [laurentnoe/yass#3]
Hi, 
I am using yass to align sequences and create a dotplot. How can I modify windowsize ? 
I also notices that the is:issue *wdsize*.mat files creates come out empty. Is that a problem ?

Thank you very much in advance,

**Comment by laurentnoe** [comment]
Hi,

there is not _windowsize_ as in a "true" dotplot, since it is an alignment tool provided with a dotplot viewer

you can change _virtually_ the windowsize :
- directly in the **dotplot tool** (online or remote) to _filter out_ yass results :
    * by using the `&maxAl=10000` parameter (add it directly in the URL), to show only 10000 most relevant alignments
    * by adding the `maxAl=10000` parameter, to the [https://github.com/laurentnoe/yass/blob/master/yass2dotplot.php](https://github.com/laurentnoe/yass/blob/master/yass2dotplot.php) command line tool

> 

- possibly in **yass** to get _better parameters_ for what you expect to align :
    * by modifying the _E-value_ (e.g. `-E 1e-6`  or `-E 1e-9`)
    * by changing the _scoring system_ to something _more_ or _less_ stringent  ( e.g `-C 1,-3 -G 8,2` or  `-C 1,-1 -G 2,1`)
    * possibly by changing the _indels and mutation parameters_ (e.g `-i 10 -m 5` ), and possibly by disabling the _post-processing step_ (e.g. `-w 0`)

>


PS : where is the " is:issue wdsize.mat" file ?
